<?php
// This file generated by Propel 1.3.0-dev convert-props target
// from XML runtime conf file G:\keeko\db\runtime-conf.xml
require KEEKO_PATH.'/config.php';

return array (
  'propel' => 
  array (
    'datasources' => 
    array (
      'keeko' => 
      array (
        'adapter' => 'mysql',
        'connection' => 
        array (
          'dsn' => 'mysql:dbname='.$dbName.';host='.$dbHost,
          'user' => $dbUser,
          'password' => $dbPass,
          'options' => 
          array (
            'ATTR_PERSISTENT' => 
            array (
              'value' => false,
            ),
          ),
          'attributes' => '
						
					',
          'settings' => 
          array (
            'charset' => 
            array (
              'value' => 'utf8',
            ),
          ),
        ),
        /*'classes' => 
        array (
          'LanguageMapBuilder' => 'net/keeko/cms/core/entities/map/LanguageMapBuilder.php',
          'LanguagePeer' => 'net/keeko/cms/core/entities/LanguagePeer.php',
          'Language' => 'net/keeko/cms/core/entities/Language.php',
          'LanguageTextMapBuilder' => 'net/keeko/cms/core/entities/map/LanguageTextMapBuilder.php',
          'LanguageTextPeer' => 'net/keeko/cms/core/entities/LanguageTextPeer.php',
          'LanguageText' => 'net/keeko/cms/core/entities/LanguageText.php',
          'PageMapBuilder' => 'net/keeko/cms/core/entities/map/PageMapBuilder.php',
          'PagePeer' => 'net/keeko/cms/core/entities/PagePeer.php',
          'Page' => 'net/keeko/cms/core/entities/Page.php',
          'LayoutMapBuilder' => 'net/keeko/cms/core/entities/map/LayoutMapBuilder.php',
          'LayoutPeer' => 'net/keeko/cms/core/entities/LayoutPeer.php',
          'Layout' => 'net/keeko/cms/core/entities/Layout.php',
          'GridMapBuilder' => 'net/keeko/cms/core/entities/map/GridMapBuilder.php',
          'GridPeer' => 'net/keeko/cms/core/entities/GridPeer.php',
          'Grid' => 'net/keeko/cms/core/entities/Grid.php',
          'UnitMapBuilder' => 'net/keeko/cms/core/entities/map/UnitMapBuilder.php',
          'UnitPeer' => 'net/keeko/cms/core/entities/UnitPeer.php',
          'Unit' => 'net/keeko/cms/core/entities/Unit.php',
          'BlockMapBuilder' => 'net/keeko/cms/core/entities/map/BlockMapBuilder.php',
          'BlockPeer' => 'net/keeko/cms/core/entities/BlockPeer.php',
          'Block' => 'net/keeko/cms/core/entities/Block.php',
          'SettingMapBuilder' => 'net/keeko/cms/core/entities/map/SettingMapBuilder.php',
          'SettingPeer' => 'net/keeko/cms/core/entities/SettingPeer.php',
          'Setting' => 'net/keeko/cms/core/entities/Setting.php',
          'SettingCatMapBuilder' => 'net/keeko/cms/core/entities/map/SettingCatMapBuilder.php',
          'SettingCatPeer' => 'net/keeko/cms/core/entities/SettingCatPeer.php',
          'SettingCat' => 'net/keeko/cms/core/entities/SettingCat.php',
          'ModuleMapBuilder' => 'net/keeko/cms/core/entities/map/ModuleMapBuilder.php',
          'ModulePeer' => 'net/keeko/cms/core/entities/ModulePeer.php',
          'Module' => 'net/keeko/cms/core/entities/Module.php',
          'ActionMapBuilder' => 'net/keeko/cms/core/entities/map/ActionMapBuilder.php',
          'ActionPeer' => 'net/keeko/cms/core/entities/ActionPeer.php',
          'Action' => 'net/keeko/cms/core/entities/Action.php',
          'MenuMapBuilder' => 'net/keeko/cms/core/entities/map/MenuMapBuilder.php',
          'MenuPeer' => 'net/keeko/cms/core/entities/MenuPeer.php',
          'Menu' => 'net/keeko/cms/core/entities/Menu.php',
          'MenuItemMapBuilder' => 'net/keeko/cms/core/entities/map/MenuItemMapBuilder.php',
          'MenuItemPeer' => 'net/keeko/cms/core/entities/MenuItemPeer.php',
          'MenuItem' => 'net/keeko/cms/core/entities/MenuItem.php',
          'RoleMapBuilder' => 'net/keeko/cms/core/entities/map/RoleMapBuilder.php',
          'RolePeer' => 'net/keeko/cms/core/entities/RolePeer.php',
          'Role' => 'net/keeko/cms/core/entities/Role.php',
          'RoleActionMapBuilder' => 'net/keeko/cms/core/entities/map/RoleActionMapBuilder.php',
          'RoleActionPeer' => 'net/keeko/cms/core/entities/RoleActionPeer.php',
          'RoleAction' => 'net/keeko/cms/core/entities/RoleAction.php',
          'UserMapBuilder' => 'net/keeko/cms/core/entities/map/UserMapBuilder.php',
          'UserPeer' => 'net/keeko/cms/core/entities/UserPeer.php',
          'User' => 'net/keeko/cms/core/entities/User.php',
          'RoleUserMapBuilder' => 'net/keeko/cms/core/entities/map/RoleUserMapBuilder.php',
          'RoleUserPeer' => 'net/keeko/cms/core/entities/RoleUserPeer.php',
          'RoleUser' => 'net/keeko/cms/core/entities/RoleUser.php',
          'PagePermissionMapBuilder' => 'net/keeko/cms/core/entities/map/PagePermissionMapBuilder.php',
          'PagePermissionPeer' => 'net/keeko/cms/core/entities/PagePermissionPeer.php',
          'PagePermission' => 'net/keeko/cms/core/entities/PagePermission.php',
          'UserSettingMapBuilder' => 'net/keeko/cms/core/entities/map/UserSettingMapBuilder.php',
          'UserSettingPeer' => 'net/keeko/cms/core/entities/UserSettingPeer.php',
          'UserSetting' => 'net/keeko/cms/core/entities/UserSetting.php',
          'UserExtMapBuilder' => 'net/keeko/cms/core/entities/map/UserExtMapBuilder.php',
          'UserExtPeer' => 'net/keeko/cms/core/entities/UserExtPeer.php',
          'UserExt' => 'net/keeko/cms/core/entities/UserExt.php',
          'UserExtCatMapBuilder' => 'net/keeko/cms/core/entities/map/UserExtCatMapBuilder.php',
          'UserExtCatPeer' => 'net/keeko/cms/core/entities/UserExtCatPeer.php',
          'UserExtCat' => 'net/keeko/cms/core/entities/UserExtCat.php',
          'UserExtValMapBuilder' => 'net/keeko/cms/core/entities/map/UserExtValMapBuilder.php',
          'UserExtValPeer' => 'net/keeko/cms/core/entities/UserExtValPeer.php',
          'UserExtVal' => 'net/keeko/cms/core/entities/UserExtVal.php',
          'PageCssMapBuilder' => 'net/keeko/cms/core/entities/map/PageCssMapBuilder.php',
          'PageCssPeer' => 'net/keeko/cms/core/entities/PageCssPeer.php',
          'PageCss' => 'net/keeko/cms/core/entities/PageCss.php',
          'PageJsMapBuilder' => 'net/keeko/cms/core/entities/map/PageJsMapBuilder.php',
          'PageJsPeer' => 'net/keeko/cms/core/entities/PageJsPeer.php',
          'PageJs' => 'net/keeko/cms/core/entities/PageJs.php',
          'UnitActionMapBuilder' => 'net/keeko/cms/core/entities/map/UnitActionMapBuilder.php',
          'UnitActionPeer' => 'net/keeko/cms/core/entities/UnitActionPeer.php',
          'UnitAction' => 'net/keeko/cms/core/entities/UnitAction.php',
          'ParamMapBuilder' => 'net/keeko/cms/core/entities/map/ParamMapBuilder.php',
          'ParamPeer' => 'net/keeko/cms/core/entities/ParamPeer.php',
          'Param' => 'net/keeko/cms/core/entities/Param.php',
          'LayoutGridMapBuilder' => 'net/keeko/cms/core/entities/map/LayoutGridMapBuilder.php',
          'LayoutGridPeer' => 'net/keeko/cms/core/entities/LayoutGridPeer.php',
          'LayoutGrid' => 'net/keeko/cms/core/entities/LayoutGrid.php',
          'BlockActionMapBuilder' => 'net/keeko/cms/core/entities/map/BlockActionMapBuilder.php',
          'BlockActionPeer' => 'net/keeko/cms/core/entities/BlockActionPeer.php',
          'BlockAction' => 'net/keeko/cms/core/entities/BlockAction.php',
          'UserSettingValueMapBuilder' => 'net/keeko/cms/core/entities/map/UserSettingValueMapBuilder.php',
          'UserSettingValuePeer' => 'net/keeko/cms/core/entities/UserSettingValuePeer.php',
          'UserSettingValue' => 'net/keeko/cms/core/entities/UserSettingValue.php',
          'SettingSectionMapBuilder' => 'net/keeko/cms/core/entities/map/SettingSectionMapBuilder.php',
          'SettingSectionPeer' => 'net/keeko/cms/core/entities/SettingSectionPeer.php',
          'SettingSection' => 'net/keeko/cms/core/entities/SettingSection.php',
        ),*/
      ),
      'default' => 'keeko',
    ),
    'generator_version' => '1.3.0-dev',
  ),
);